# Generated by Django 4.2.13 on 2024-07-31 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='heading',
        ),
    ]
