# Generated by Django 4.2.13 on 2024-07-31 11:56

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_product_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1200, 630], upload_to='product/'),
        ),
    ]
