# Generated by Django 4.2.13 on 2024-08-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='top_seller',
            field=models.BooleanField(default=False),
        ),
    ]
