# Generated by Django 4.2.13 on 2024-08-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
