# Generated by Django 4.2.13 on 2024-08-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_remove_order_email_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
